#!/bin/sh

version=$(git describe --abbrev=0 --tags)
name="xsv2-$version-x86_64-unknown-linux-gnu"

github-release release --user faradayio --repo xsv2 --tag $version \
  --name "xsv2-$version" --pre-release
